apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment

configMapGenerator:
  - name: order-config
    behavior: merge
    literals:
      - log-level=debug
  - name: payment-config
    behavior: merge
    literals:
      - log-level=debug
  - name: fulfillment-config
    behavior: merge
    literals:
      - log-level=debug
