apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
data:
  brokers: "kafka-broker-0.kafka:9092,kafka-broker-1.kafka:9092,kafka-broker-2.kafka:9092"
  order-events-topic: "order-events"
  payment-events-topic: "payment-events"
  fulfillment-events-topic: "fulfillment-events"
