apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - kafka-config.yaml
  - mongodb-secret.yaml
  - order/
  - payment/
  - fulfillment/

commonLabels:
  app.kubernetes.io/part-of: ecommerce-platform
  app.kubernetes.io/managed-by: kustomize
