apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment

configMapGenerator:
  - name: order-config
    behavior: merge
    literals:
      - log-level=info
  - name: payment-config
    behavior: merge
    literals:
      - log-level=info
  - name: fulfillment-config
    behavior: merge
    literals:
      - log-level=info
